version: "3"
services:
  haystack-api:
    build:
      context: ../../../docker
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
    image: "intel/ai-workflows:odqa-haystack-api"
    network_mode: host
    # Mount custom Pipeline YAML and custom Components.
    volumes:
      - $CUSTOMER_DIR:/home/user/data
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      # See rest_api/pipeline/pipelines.haystack-pipeline.yml for configurations of Search & Indexing Pipeline.
      - PIPELINE_YAML_PATH=$PIPELINE_PATH
      - QUERY_PIPELINE_NAME=$PIPELINE_NAME
      - INDEX_NAME=$INDEX_NAME
      - CONCURRENT_REQUEST_PER_WORKER
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - no_proxy=$no_proxy
      #- ONEDNN_VERBOSE=1
      - KMP_BLOCKTIME=20
      - MKL_ENABLE_INSTRUCTIONS=AVX512_E1
      - LD_PRELOAD=/usr/local/lib/libiomp5.so
      - KMP_AFFINITY=granularity=fine,verbose,compact,1,0
      #- MKL_VERBOSE=1
    depends_on:
      - postsql-db
    # Starts REST API with only 2 workers so that it can be run on systems with just 4GB of memory
    # If you need to handle large loads of incoming requests and have memory to spare, consider increasing the number of workers
    command: "/bin/bash -c 'sleep 10 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 600'"
  postsql-db:
    image: "postgres:14.1-alpine"
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=$POSTGRES_HOST_AUTH_METHOD
    volumes:
      - $DATA_DIR:/var/lib/postgresql/data

  ui:
    build:
      context: ../../../ui
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
    image: "intel/ai-workflows:odqa-haystack-ui"
    network_mode: host
    ports:
      - 8501:8501
    restart: on-failure
    volumes:
      - $UI_CONFIG_DIR:/home/user/data/
    environment:
      - API_ENDPOINT=http://localhost:8000
      - EVAL_FILE=ui/eval_labels_example.csv
      - PIPELINE_PATH=$PIPELINE_PATH
      # The value fot the following variables will be read from the host, if present.
      # They can also be temporarily set for docker-compose, for example:
      # DISABLE_FILE_UPLOAD=1 DEFAULT_DOCS_FROM_RETRIEVER=5 docker-compose up
      - DISABLE_FILE_UPLOAD=True
      - DEFAULT_QUESTION_AT_STARTUP
      - DEFAULT_DOCS_FROM_RETRIEVER
      - DEFAULT_NUMBER_OF_ANSWERS
    command: "/bin/bash -c 'sleep 15 && python -m streamlit run ui/webapp.py'"
