FROM ubuntu:20.04

WORKDIR /home/user

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3  \
    python3-pip \
    wget \
    git \
    libpoppler-cpp-dev  \
    tesseract-ocr  \
    tesseract-ocr-chi-sim \
    libtesseract-dev  \
    poppler-utils && \
    rm -rf /var/lib/apt/lists/*

# Install PDF converter
RUN wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && \
    tar -xvf xpdf-tools-linux-4.04.tar.gz && cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

#clone the code repo
RUN git clone --depth=1 https://github.com/intel/open-domain-question-and-answer.git
WORKDIR /home/user/open-domain-question-and-answer
RUN git submodule update --init --recursive
RUN ln -s /usr/bin/python3.8 /usr/bin/python
# Install package
RUN pip install --upgrade pip
#RUN pip install --no-cache-dir .[docstores,crawler,preprocessing,ocr,ray]
RUN pip install --no-cache-dir .[faiss]
RUN pip install --no-cache-dir third_party/ColBERT/
RUN pip install ray[all]==2.2.0
#RUN pip install -U ray[default]
RUN pip install pyarrow 
RUN pip install numba
RUN pip install datasets
RUN pip install ujson
RUN pip install pytesseract
RUN pip install kaggle
RUN pip install fastapi
RUN pip install modin[all]
RUN ls /home/user
RUN pip freeze



EXPOSE 8000
EXPOSE 6379
EXPOSE 8266
ENV HAYSTACK_DOCKER_CONTAINER="HAYSTACK_CPU_CONTAINER"
ENV HAYSTACK_TELEMETRY_ENABLED="False"

